---
ID: "13f87148-b4ea-439c-88de-cc6d2d4315e2"
Parent: "1be47cdd-f7d8-4f87-aa60-b249ac75f076"
Template: "1be47cdd-f7d8-4f87-aa60-b249ac75f076"
Path: /sitecore/templates/Project/demo/Headless Site/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230725T165851Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Morten Ljungberg
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Morten Ljungberg
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2c094cf0-71d9-4ee2-a1af-3bad2fc4ae97"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Morten Ljungberg
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230725T165851Z
