---
ID: "afbcf76c-cec1-41c0-9d5d-4c89f88493fa"
Parent: "0a9881f5-fe95-4a19-9e93-e3a8ad1cd23a"
Template: "c14bf746-030f-4e59-8594-395f6d299e61"
Path: /sitecore/content/demo/demo/Settings/Shared Sites Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230725T165905Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Morten Ljungberg
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Morten Ljungberg
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9d77a25c-73c2-4e63-a4de-92e9db97d7ba"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Morten Ljungberg
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230725T165905Z
